version: "3.7"

services:
  node-ts:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: batida-ponto
    volumes:
      - ./src:/usr/app/src
    networks:
      - app
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    command: bash -c "
      npm run migrate &&
      npm run generate &&
      npm run dev"
     
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app
    env_file:
      - .env
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=default
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  app:
    driver: bridge

volumes:
  postgres:
    name: postgres
