version: "3.7"

services:
  node-ts:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: batida-ponto
    volumes:
      - ./src:/usr/app/src
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    links:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=default
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres
