version: "3.7"

services:
  node-ts:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: batida-ponto
    volumes:
      - ./src:/usr/app/src
    ports:
      - "3333:3333"
      - "8181:8181"
    command: npm run dev
